
---
title: "logistic regression"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(tidyr)
library(broom)
library(ggplot2)

file="reviews_english.csv"
#file="reviews_schinese.csv"
reviews <- read.csv(file, stringsAsFactors = FALSE)
#reviews_new <- na.omit(reviews)
reviews=reviews[1:50,]

# Data type conversions
reviews$voted_up <- as.logical(reviews$voted_up)
reviews$steam_purchase <- as.logical(reviews$steam_purchase)
reviews$received_for_free <- as.logical(reviews$received_for_free)
reviews$written_during_early_access <- as.logical(reviews$written_during_early_access)
reviews$hidden_in_steam_china <- as.logical(reviews$hidden_in_steam_china)
reviews$timestamp_created <- as.POSIXct(reviews$timestamp_created, origin = "1970-01-01")
reviews$timestamp_updated <- as.POSIXct(reviews$timestamp_updated, origin = "1970-01-01")
reviews$author_last_played <- as.POSIXct(reviews$author_last_played, origin = "1970-01-01")

model <- lm(voted_up ~ author_playtime_forever + author_num_games_owned + author_num_reviews+votes_up + votes_funny+steam_purchase + received_for_free + written_during_early_access, data = reviews)  # Full model with all independent variables
step_model <- step(model, direction = "both")  # Perform stepwise iteration

model <- glm(voted_up ~ author_playtime_forever + author_num_games_owned + votes_up + steam_purchase + written_during_early_access+comment_count, data = reviews, family=binomial(link="logit"))
```



```{r}
#test assumptions!
# Predict the probability (p) of positivity
model <- glm(voted_up ~ author_playtime_forever + author_num_games_owned + votes_up + steam_purchase + written_during_early_access+comment_count, data = reviews, family=binomial(link="logit"))
probabilities<- predict(model, type = "response")[1:length(reviews[,1])] 
predicted.classes <- ifelse(probabilities > 0.5, "pos", "neg")
# Select only numeric predictors
mydata <- reviews %>%
  dplyr::select_if(is.numeric) 
predictors <- colnames(mydata)

# Bind the logit and tidying the data for plot
#probabilities=mean(probabilities)
mydata <- reviews %>%
  mutate(logit = log(probabilities/(1-probabilities))) %>% #mean(probabilities)
  gather(key = "predictors", value = "predictor.value", -logit)

ggplot(mydata, aes(logit, predictor.value))+
  geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "loess", span = 0.75) + 
  theme_bw() + 
  facet_wrap(~predictors, scales = "free_y")
#mydata$steam_purchase
#linearity of many variables we are using are met, but some are not

plot(model, which = 4, id.n = 3) # one extreme outlier

model.data <- augment(model) %>% 
  mutate(index = 1:n()) 
ggplot(model.data, aes(index, .std.resid)) + 
  geom_point(aes(color = voted_up), alpha = .5) +
  theme_bw()
#variance of the residuals is somewhat constant across all levels of the predictor variables
```

